### ISSUE TITLE
Build failing when using TCPM with CMSIS RTOS V2

### ISSUE THREAD

**Issue by rwardd** [STMicroelectronics/stm32-mw-usbpd-core#2]
# Overview
When implementing the middleware into a project using V2 of the CMSIS RTOS, and having the TCPM mode enabled, the build fails, as two of the RTOS message calls are either incorrect or missing parameters. 
# Details
The first instance is ```osMessageQueueGet``` is missing the ```event``` parameter, and the second is during the linking stage, when the linker cannot see a reference to osMessagePut, as this function does not exist in the V2 RTOS. I have made the appropriate changes to add the ```event``` variable in, and used the correct function macro definition to handle the osMessageQueuePut function calls.

# Screenshots
![Screenshot from 2024-02-13 09-12-44](https://github.com/STMicroelectronics/stm32-mw-usbpd-core/assets/63398895/5a76ecd9-1088-41b3-9f3b-45cd38012551)
![Screenshot from 2024-02-13 09-19-34](https://github.com/STMicroelectronics/stm32-mw-usbpd-core/assets/63398895/63e61d9c-2a24-4a48-9556-d56132255bbd)

**Comment by HFISTM** [comment]
ST Internal Reference: 173696
